//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitiosPruebaMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sitio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sitio()
        {
            this.Informantes = new HashSet<Informante>();
            this.Testigos = new HashSet<Testigo>();
            this.Victimas = new HashSet<Victima>();
        }
    
        public int Id_Sitio { get; set; }
        public string CodigoSitio { get; set; }
        public System.Data.Entity.Spatial.DbGeography Ubicacion { get; set; }
        public Nullable<int> Propiedad { get; set; }
        public string Antecedentes { get; set; }
        public string RelatoAcontecimientos { get; set; }
        public Nullable<System.DateTime> FechaEvento { get; set; }
        public Nullable<System.DateTime> FechaInhumacion { get; set; }
        public Nullable<decimal> NumeroVictimas { get; set; }
        public Nullable<bool> ExhumacionAnterior { get; set; }
        public Nullable<bool> MaterialesAdicionales { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Informante> Informantes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Testigo> Testigos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Victima> Victimas { get; set; }
    }
}
