//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitiosPruebaMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Victima
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Victima()
        {
            this.Familiares = new HashSet<Familiare>();
        }
    
        public int Id_Victima { get; set; }
        public string CodigoVictima { get; set; }
        public string NA { get; set; }
        public Nullable<int> Sexo { get; set; }
        public Nullable<decimal> Edad { get; set; }
        public string Procedencia { get; set; }
        public string Familia { get; set; }
        public string PresuntaAfiliacion { get; set; }
        public Nullable<int> Id_Sitio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Familiare> Familiares { get; set; }
        public virtual Sitio Sitio { get; set; }
    }
}
